spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT
    username: root
    password: 1234567
    driver-class-name: com.mysql.jdbc.Driver
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
##日志级别  可以看到在mybatis中执行的sql
logging:
  level:
    com.example.ehcache.dao: debug #指定了包名，不指定的话就是全部目录

mybatis:
  type-aliases-package: com.example.ehcache.dao
  mapper-locations: classpath:mapper/*.xml


server:
  port: 8080