
##端口号
server:
  port: 8888

##日志级别  可以看到在mybatis中执行的sql
logging:
  level:
    org.example.pagehelper.dao: debug #指定了包名，不指定的话就是全部目录


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT
    username: root
    password: 1234567
    driver-class-name: com.mysql.jdbc.Driver
#分页插件配置
pagehelper:
  reasonable: true
  helperDialect: mysql
#mybatis配置
mybatis:
  type-aliases-package: org.example.pagehelper.pojo
  mapper-locations:
    - classpath: mybatis/mapper/*.xml
