
server:
  port: 8080

##日志级别  可以看到在mybatis中执行的sql
logging:
  level:
    org.example.pagehelper.demo.dao: debug #指定了包名，不指定的话就是全部目录

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT
    username: root
    password: 1234567
    driver-class-name: com.mysql.jdbc.Driver

#Mybatis配置
mybatis:
  type-aliases-package: cn.howieli.boot.model
  mapper-locations:
    - classpath:mapper/*.xml

#分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql